id: P005603
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W00KG02353
  title: མགོ་ལོག་རིག་གནས་ལོ་རྒྱུས། （༤）
  author: ''
  volumes:
    a8da73c3ae8840a7ba7c9c2a108ffab7:
      image_group_id: I00KG02357
      title: ''
      volume_number: 1
      total_pages: 232
      base_file: v001.txt
