id: IDAD4D08F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T12:31:31+00:00'
last_modified: '2022-06-08T05:13:36.822982+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG02353
  title: མགོ་ལོག་རིག་གནས་ལོ་རྒྱུས། （༤）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4A8B:
      image_group_id: I00KG02357
      title: ''
      total_pages: 232
      order: 1
      base_file: 4A8B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
